# -*- coding: utf-8 -*-
"""
Created on Tue Aug 19 16:40:37 2014
Each new term in the Fibonacci sequence is generated by adding the previous 
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not 
exceed four million, find the sum of the even-valued terms.

O(n) complexity (simple iteration with O(1) operations)
@author: tenz
"""

def evenFibNumbers(N):
    i = 1
    j = 2
    k = 3
    
    total = 2
    
    while k < N:
        i = j
        j = k
        k = i+j
        if k % 2 == 0:
            total += k
    
    return total